import type { Metadata } from 'next';
import { Inter, Space_Grotesk as SpaceGrotesk } from 'next/font/google';

import { cn } from '@/lib/utils';
import { RootLayoutProps } from '@/types/global';

import '@/styles/global.css';

export const fontInter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

export const fontSpaceGrotesk = SpaceGrotesk({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-spaceGrotesk',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          'min-h-screen bg-background font-inter antialiased',
          fontInter.variable,
          fontSpaceGrotesk.variable,
        )}
      >
        {children}
      </body>
    </html>
  );
}
